### ISSUE TITLE
Document resolver should NOT return error on conflicting operations

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/sidetree-core-go#119]
When the document resolver determines that there are conflicting operations, e.g. two create operations for the same unique suffix, then it should discard the second create (based on transaction time and number). Currently an error is returned if there are two creates for the same unique suffix: 'create has to be the first operation'.

**Comment by sandrask** [comment]
This is not a bug, the spec works this way. We can have a look at resolving it differently (if necessary)

**Comment by bstasyszyn** [comment]
This bug will be fixed with issue #124
