### ISSUE TITLE
Update operation is not applied

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/sidetree-core-go#132]
There are various issues with the update operation:
- Update helper sets the operation type as 'create'
- The UpdateOTP is not set on the operation
- The REST handler looks fro 'uniqueSuffix' but 'didUniqueSuffix' is sent by the Update helper
- Operations are filtered based on transaction number but should be filtered first by transactionTime and then by transactionNumber 
- Operations should be sorted by transactionTime/transactionNumber

**Comment by sandrask** [comment]
Fixed as part of #137
