### ISSUE TITLE
Update to support swagger definition

### ISSUE THREAD

**Issue by troyronda** [trustbloc/sidetree-core-go#190]
See swagger: https://identity.foundation/sidetree/docs/swagger/

1. rename JSON keys according https://identity.foundation/sidetree/docs/spec
2. update our paths to match swagger (URL prefix/sidetree/operations)
3. base64URL encode the operation request to /sidetree/operations
4. update our resolution to match swagger (URL prefix/sidetree).

Example of prefix:
`https://peer1.org1.foo.com/<document type>/`

5. have an optional default document type. The default document type would alias `/sidetree` to `/<default document type>/sidetree`.

**Comment by sandrask** [comment]
this was done in different PRs
