### ISSUE TITLE
Validate signature for update operation

### ISSUE THREAD

**Issue by sandrask** [trustbloc/sidetree-core-go#193]
For update operation validate signature against key in the document.

**Comment by troyronda** [comment]
The reference implementation might be different for the update operation:

https://github.com/decentralized-identity/sidetree/blob/284420cb5b478ee96fb1576e703babc7067ad2f0/lib/core/versions/latest/DocumentComposer.ts#L114

**Comment by troyronda** [comment]
https://github.com/decentralized-identity/sidetree/blob/284420cb5b478ee96fb1576e703babc7067ad2f0/lib/core/versions/latest/DocumentComposer.ts#L257

**Comment by troyronda** [comment]
The code seems to check that the key exists in the document with usage ops.
