### ISSUE TITLE
Review did suffix generation

### ISSUE THREAD

**Issue by sandrask** [trustbloc/sidetree-core-go#212]
Related to:
-- more formal description of generation
--  canonicalization requirement

**Comment by troyronda** [comment]
also https://github.com/trustbloc/sidetree-core-go/issues/213

**Comment by troyronda** [comment]
https://identity.foundation/sidetree/spec/#did-suffix-composition

**Comment by sandrask** [comment]
Reviewed, invalid char '=' in did has been fixed with adding no padding option  #218
Use JCS RFC for Canonicalization will be fixed #213
