### ISSUE TITLE
REST API endpoints to return Sidetree protocol parameters and protocol version

### ISSUE THREAD

**Issue by troyronda** [trustbloc/sidetree-core-go#225]
Parameter reference: https://identity.foundation/sidetree/spec/#default-parameters
Protocol version reference: https://identity.foundation/sidetree/spec/#new-version-activation

- return the defined parameters at a blockchain time
- return protocol version at a blockchain time
- assume endpoint `GET` `/sidetree/config` or `/sidetree/parameters` or `/sidetree/version`?
- should we return the latest if no blockchain time is provided? 
  - assume we also need to return the blockchain time for the parameters?
- should the component info & component version be separate or combined? #226
  - `/sidetree/version`

**Comment by bstasyszyn** [comment]
Moved this issue to https://github.com/trustbloc/sidetree-fabric/issues/432.
