### ISSUE TITLE
Validate ietf-json-patch doesn't affect keys

### ISSUE THREAD

**Issue by troyronda** [trustbloc/sidetree-core-go#253]
The DID document PublicKey and defined verification method sections should not be changed by ietf-json-patch actions. We need to add validation logic to drop patches that attempt to do this.

This validation logic should be performed when observing changes from the blockchain. We should also check at ingestion to reduce the number of invalid patches being written.

We want to avoid ietf-json-patch actions resulting in unrecoverable states, similar to "Deactivated".

**Comment by sandrask** [comment]
I have todo and issue for this: https://github.com/trustbloc/sidetree-core-go/issues/175

**Comment by sandrask** [comment]
This is specific one though so we should keep it.
