### ISSUE TITLE
Resolution result differences (comparing to reference)

### ISSUE THREAD

**Issue by sandrask** [trustbloc/sidetree-core-go#333]
There are multiple differences in resolution result rendering when compared to reference implementation. Reference implementation has following features:

1) resolution with initial state returns as document 'id' whole initial state URL

Trustbloc:
id: 'did:sidetree:EiDyGboJMdFeEPF7UEt4yuJ0AHAmElPcdmOQhoCg_DV_pw' 

Reference implementation: 
  id: 'did:sidetree:EiDyGboJMdFeEPF7UEt4yuJ0AHAmElPcdmOQhoCg_DV_pw?-sidetree-initial-state=eyJkZWx0YV9oYXNoIjoiRWlDX1V3NlgwT2c0cmhVYkQ5YjhwMmhSSUhSMVVSbUc5OHdmYzZ0dFNENTZHdyIsInJlY292ZXJ5X2NvbW1pdG1lbnQiOiJFaUJVX3hZdC1kQnMzVU1RMEpIZWFKSVdBQmVCeXNPb0ROc0s2bFhZd05JcXNBIn0.eyJ1cGRhdGVfY29tbWl0bWVudCI6IkVpQ3E1M3VCV29odGxaVWdUdjhmZGF2blhGWEJGelBJTE5pS0UxZHp5ZzJXd2ciLCJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljX2tleXMiOlt7ImlkIjoic2lnbmluZ0tleSIsInR5cGUiOiJFY2RzYVNlY3AyNTZrMVZlcmlmaWNhdGlvbktleTIwMTkiLCJqd2siOnsia3R5IjoiRUMiLCJjcnYiOiJzZWNwMjU2azEiLCJ4IjoialROZlluMmpNTUlYQUJCa20zc01XN1E3ZGEwOVY5T2tiaFNqZUQ1b09JVSIsInkiOiJ3VURIRk5pREgxUlpoOXJEbmhRZ0pRdHF0MHdUX1hXM0x4TmVKbzVCLXRJIn0sInB1cnBvc2UiOlsiYXV0aCIsImdlbmVyYWwiXX1dLCJzZXJ2aWNlX2VuZHBvaW50cyI6W3siaWQiOiJzZXJ2aWNlRW5kcG9pbnRJZDEyMyIsInR5cGUiOiJzb21lVHlwZSIsImVuZHBvaW50IjoiaHR0cHM6Ly93d3cudXJsLmNvbSJ9XX19XX0'

2) ids (public keys, services) start with # (they are not appending DID before #)

Trustbloc:
id 'did:sidetree:EiDyGboJMdFeEPF7UEt4yuJ0AHAmElPcdmOQhoCg_DV_pw#key2' 

Reference implementation:
id:  '#key2' 

3) public key controller is empty 

Trustbloc: 
controller: 'did:sidetree:EiDyGboJMdFeEPF7UEt4yuJ0AHAmElPcdmOQhoCg_DV_pw'
Reference implementation: 
controller: ''

4) @base property

Reference implentation has @base property:
  '@context': [
    'https://www.w3.org/ns/did/v1',
    {
      '@base': 'did:sidetree:EiD3SvGXdmofxyEOuxtVzSf0AVzC4LRAVZyZoKCmWs9IsQ'
    }
  ],

Trustbloc doesn't have @base property

5) reference implementation is not returning published flag

Currently reference implementation is not returning published flag

6) Resolution spec still states that deactivate is still under discussion. 
Trustbloc returns status 410 (gone) and no resolution result
Reference implementation is returning { status: 'deactivated' };
 

Note: Issues 2, 3 and 4 might be related if reference implementation is having additional transformation somewhere else ...

**Comment by sandrask** [comment]
[DID.txt](https://github.com/trustbloc/sidetree-core-go/files/4833786/DID.txt)
[DIDResolution.txt](https://github.com/trustbloc/sidetree-core-go/files/4833787/DIDResolution.txt)
[InitValueDID.txt](https://github.com/trustbloc/sidetree-core-go/files/4833788/InitValueDID.txt)
[InitValueResolutionResult.txt](https://github.com/trustbloc/sidetree-core-go/files/4833789/InitValueResolutionResult.txt)

**Comment by troyronda** [comment]
- Re 1: The Sidetree WG believes that it is correct to include the initial state query parameter. They are bringing this up as an issue in DID core to clarify.
- Re 2: I believe this is being treated as a relative URI to `@base`.
- Re 3: In the [JSON-LD 1.1 spec example 17](https://json-ld.org/spec/latest/json-ld/#example-17-use-a-relative-iri-as-node-identifier), I see that a blank `@id` can refer to `@base`. I assume blank controller with `@base` has the same meaning but there isn't an explicit example in DID core.
- Re 5: The Sidetree reference implementors still intend to add this flag.

**Comment by sandrask** [comment]
It looks to me that I only need to address number 1) @troyronda

**Comment by troyronda** [comment]
@sandrask re: 1 - it is still being discussed. E.g., https://github.com/decentralized-identity/sidetree/issues/782#issuecomment-654412611

**Comment by sandrask** [comment]
Difference number 5 and 6 have been fixed in reference application 
Difference number 1 has been fixed in our implementation with #398

**Comment by sandrask** [comment]
Issue 2 had been addressed with handling @base property
Issue 1 has been addressed with handling long form id

I am closing this issue since there are no differences in output between our app and reference app
