### ISSUE TITLE
remove validation of optional `service` properties

### ISSUE THREAD

**Issue by llorllale** [trustbloc/sidetree-core-go#335]
The sidetree spec mandates the inclusion of `id`, `type`, and `endpoint` in each `service` entry: https://identity.foundation/sidetree/spec/#add-service-endpoints.

Beyond those, it does not prescribe any limitation on additional fields that may be included. [This](https://github.com/trustbloc/sidetree-core-go/blob/a0a41f22840d68d327d1ac15dec10206f2078a29/pkg/document/validator.go#L123) check should therefore be removed.

**Comment by sandrask** [comment]
A month ago or so spec allowed only for "MUST" properties and @troyronda wanted to include additional properties only if they are on 'allowed' list. @troyronda  Do you still want a check for properties added in add-service-endpoint patch or I should I remove check as @llorllale suggested?

**Comment by sandrask** [comment]
@troyronda any decisions on my comment above

**Comment by llorllale** [comment]
@sandrask @troyronda checks for specific fields outside those absolutely required by did-core (`id`, `type`, `endpoint`) would encumber extensions to did documents (ie. custom vocabularies that extend `service` entries).

**Comment by sandrask** [comment]
@llorllale I agree that removing restrictions is more flexible so I am for it @troyronda just has to confirm it is ok to remove allowed list (since it was his idea to create it)

**Comment by sandrask** [comment]
After discussion with @llorllale and @troyronda it has been decided to disable validation of optional service endpoint fields. New issue has been created #373
