### ISSUE TITLE
Review rule for "kid MUST be present in the protected header"

### ISSUE THREAD

**Issue by sandrask** [trustbloc/sidetree-core-go#365]
There is discrepancy between spec "kid MUST be present in the protected header" and reference implementation that expects only one 'alg' header. If I implement spec version interop tests are failing.

https://github.com/decentralized-identity/sidetree/blob/0dbf2c8ce6ef8981ebc6735066841bce39e2648f/lib/core/versions/latest/util/Jws.ts#L40

 // TODO: There is discrepancy between spec "kid MUST be present in the protected header"
https://github.com/trustbloc/sidetree-core-go/blob/79fd877c13d96ea2d1999439d261c38e9a2f1ff8/pkg/operation/recover.go#L127

**Comment by troyronda** [comment]
https://github.com/decentralized-identity/sidetree/issues/841

**Comment by sandrask** [comment]
The spec was changed to "kid MAY be present in the protected header" - will remove commented out code and issue reference from the code.
