### ISSUE TITLE
Evaluate usage of @base

### ISSUE THREAD

**Issue by sandrask** [trustbloc/sidetree-core-go#370]
If the DID Document is being rendered in the JSON-LD representation variant, the implementer SHOULD add an @base entry to the document’s @context, and set the @base value to the id of the resolved DID. This ensures relative path values in the output DID Document are correctly projected into id-related strings by JSON-LD parsers.

**Comment by sandrask** [comment]
Currently aries cannot parse did document with @base context. Here is sample reference implementation DID.
`{
  "id": "did:sidetree:EiBFsUlzmZ3zJtSFeQKwJNtngjmB51ehMWWDuptf9b4Bag",
  "@context": [
    "https://www.w3.org/ns/did/v1",
    {
      "@base": "did:sidetree:EiBFsUlzmZ3zJtSFeQKwJNtngjmB51ehMWWDuptf9b4Bag"
    }
  ],
  "service": [
    {
      "id": "#serviceEndpointId123",
      "type": "someType",
      "serviceEndpoint": "https://www.url.com"
    }
  ],
  "publicKey": [
    {
      "id": "#signingKey",
      "controller": "",
      "type": "EcdsaSecp256k1VerificationKey2019",
      "publicKeyJwk": {
        "kty": "EC",
        "crv": "secp256k1",
        "x": "y9kzrVBqXx24sVMEQQk4Ce-0bqZ1i5TwxllWCkzA7wU",
        "y": "c2JHxQqUUtyWILAIicmpBGC47PgmJT465tPocG2q18k"
      }
    }
  ],
  "authentication": [
    "#signingKey"
  ]
}`

**Comment by llorllale** [comment]
@sandrask what's the error?

**Comment by llorllale** [comment]
```
panic: interface conversion: interface {} is map[string]interface {}, not string [recovered]
	panic: interface conversion: interface {} is map[string]interface {}, not string
```

**Comment by sandrask** [comment]
@llorllale There is panic in ParseDocument (specifically parse context part:
/usr/local/go/src/runtime/panic.go:679 +0x1b2
aries-framework-go/pkg/doc/did.(*rawDoc).ParseContext(0xc00023b0e0, 0xc0000ce6d8, 0x0, 0x0)
/aries-framework-go/pkg/doc/did/doc.go:600 +0x32a

**Comment by llorllale** [comment]
opened hyperledger/aries-framework-go#2133 to track this

**Comment by llorllale** [comment]
@sandrask is this fix needed by next monday?

**Comment by sandrask** [comment]
No, it is not needed



> @sandrask is this fix needed by next monday?
no, we can look into this in September. Trustbloc sidetree doesn't have @base property in did document and we (@troyronda) are still not sure if we should include it like reference app. I am currently reading about it - it is not clear in did spec.

**Comment by llorllale** [comment]
Relevant part of the sidetree spec:

> If the DID Document is being rendered in the JSON-LD representation variant, the implementer SHOULD add an `@base` entry to the document’s `@context`, and set the `@base` value to the id of the resolved DID. This ensures relative path values in the output DID Document are correctly projected into id-related strings by JSON-LD parsers.

Relevant part of the [did-core spec](https://www.w3.org/TR/did-core/#production-0):

> The value of the `@context` property MUST be one or more URIs, where the value of the first URI is https://www.w3.org/ns/did/v1. All members of the `@context` property MUST exist be in the DID properties extension registry. 

The sidetree spec seems to be conflicting with did-core.

**Comment by sandrask** [comment]
@llorllale I agree with you. @troyronda mentioned that aries-framework should still be able to process @base (so we can process reference implementation DIDs)

**Comment by troyronda** [comment]
Yes, we we want to be able to able to process the current Sidetree implementation DIDs (including did:trustbloc, did:elem, did:ion and reference implementation DIDs).

**Comment by llorllale** [comment]
decentralized-identity/sidetree#842

Sidetree may end up using relative URLs as [described in did-core](https://w3c.github.io/did-core/#relative-did-urls).

**Comment by llorllale** [comment]
From #447:

> Let's add the @base property as an option for the DID document transformation. This capability will allow us to fully test against the sidetree interop fixtures.

> We will need this to be configurable since aries-framework-go doesn’t currently support it. We should also fix aries-framework-go as a followup.

cc @troyronda

**Comment by llorllale** [comment]
The framework's parsers need to respect the content's type.

**Comment by sandrask** [comment]
Completed in merged  pull request
