### ISSUE TITLE
spec: if apply patch fails for update operation exit update operation processing and advance to compiled state processing

### ISSUE THREAD

**Issue by sandrask** [trustbloc/sidetree-core-go#385]
@troyronda 

As per spec If there is an error during update operation processing you are supposed to stop processing (it is not going to next operation for that commitment value). In this case there is no ability to issue another valid update operation to correct the situation.

On the other hand, reference app is applying first valid update operation for that commitment value. We are doing the same as reference application.

Spec:
Begin iterating the patches array in the Chunk File Delta Entry, and for each DID State Patch entry, perform the following steps:
Validate the entry in accordance any requirements imposed by the Patch Action type indicated by the action value of the entry. If the entry is valid, proceed, if the entry fails validation, exit update operation processing and advance to compiled state processing.
Apply the patch as directed by the Patch Action type specified by the action property. If any part of the patch fails or produces an error, reverse all modifications to the DID’s state and exit update operation processing and advance to compiled state processing.

**Comment by troyronda** [comment]
@sandrask My thought is that the reference implementation is correct - a patch error should result in advancing the loop to the next operation NOT exiting processing.

**Comment by sandrask** [comment]
Scheduled to be discussed at the next DIFF Sidetree weekly meeting - most likely just spec issue.

**Comment by sandrask** [comment]
One part of this issue has been fixed with #510, also spec will be modified as per latest Sidetree weekly so this is now outdated.
