### ISSUE TITLE
Update JSON APIs according to style guide

### ISSUE THREAD

**Issue by troyronda** [trustbloc/sidetree-core-go#444]
See https://github.com/decentralized-identity/sidetree/pull/881

- [Microsoft API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md) 
- [Google JSON Style Guide](https://google.github.io/styleguide/jsoncstyleguide.xml)
- [JSON API](https://jsonapi.org/recommendations)
- [RESTful API Guidelines](https://restfulapi.net/)

**Comment by sandrask** [comment]
PR 881 contains a lot more functionality than just renaming as per style guides - details will be listed in merge PR.
