### ISSUE TITLE
Support base via option / configuration

### ISSUE THREAD

**Issue by troyronda** [trustbloc/sidetree-core-go#447]
Let's add the `@base` property as an option for the DID document transformation. This capability will allow us to fully test against the sidetree interop fixtures.

We will need this to be configurable since `aries-framework-go` doesn’t currently support it. We should also fix aries-framework-go as a followup.

**Comment by llorllale** [comment]
@troyronda 

> We should also fix aries-framework-go as a followup.

Framework parsers should respect the content type.

**Comment by llorllale** [comment]
Also this is a duplicate of #370
