### ISSUE TITLE
Clarify ZIP compression

### ISSUE THREAD

**Issue by sandrask** [trustbloc/sidetree-core-go#478]
Spec is referencing ZIP compression as suggested default in protocol parameters. Reference implementation is using gzip: https://github.com/decentralized-identity/sidetree/blob/ed1999209a45fd1cb8426a30c2b50724a1a2f937/lib/core/versions/latest/util/Compressor.ts#L22

We are using gzip compression but we specify it as "GZIP".  Clarify this with @troyronda

**Comment by sandrask** [comment]
@troyronda confirmed that we should use GZIP, opened up spec issue:  https://github.com/decentralized-identity/sidetree/issues/925

**Comment by troyronda** [comment]
@sandrask spec issue resolved.
