### ISSUE TITLE
Align resolution object with did core spec

### ISSUE THREAD

**Issue by sandrask** [trustbloc/sidetree-core-go#534]
Align resolution object with did core spec:

    "didDocumentMetadata": {
        "method": {
            "published": boolean,
            "updateCommitment": UPDATE_COMMITMENT,
            "recoveryCommitment": RECOVERY_COMMITMENT
        }
    }

Change the result of deactivate in the reference implementation to align better with did-core spec. It will be returned as an empty document with only id and context, and metadata logic remains the same.

https://github.com/decentralized-identity/sidetree/pull/1000

**Comment by isaacJChen** [comment]
Not sure if this matters to you guys, but we also changed the result of deactivate to align better with did-core spec. It will be returned as an empty document with only id and context, and metadata logic remains the same.
![image](https://user-images.githubusercontent.com/26752423/104056299-20ff7b80-51a5-11eb-8fcd-bc87f5e9b15e.png)

**Comment by sandrask** [comment]
@isaacJChen thanks a lot for clarifying, I updated issue comment to include "deactivate" changes too. I usually inspect your PR in detail once I get to it.
