### ISSUE TITLE
Implement Sidetree REST API for DID documents

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/sidetree-core-go#54]
Add REST API endpoints according to the Sidetree spec for DID documents. (Currently the REST APIs are implemented in sidetree-node.)

**Comment by troyronda** [comment]
I assume this means that sidetree-node repo becomes deprecated and we should instead build the docker image from sidetree-core-go?

We should generate the OpenAPI spec using comment annotations. (Similar to what was done in aries-framework-go.) Example: https://github.com/hyperledger/aries-framework-go/blob/master/pkg/restapi/operation/didexchange/didexchange.go#L119

@bstasyszyn @fqutishat

**Comment by troyronda** [comment]
We also need to extend the Fabric peer to support the APIs directly - without having a second binary. @bstasyszyn
