### ISSUE TITLE
Add relevant key context to did document

### ISSUE THREAD

**Issue by sandrask** [trustbloc/sidetree-core-go#570]
DID WG is deleting  crypto suite’s contexts from the core did context.
Add relevant context to did document (based on the public key types that are actually in the did document).

For example:
JSONWebKey https://w3c-ccg.github.io/lds-jws2020/contexts/lds-jws2020-v1.json
BBS: https://w3id.org/security/bbs/v1

**Comment by troyronda** [comment]
Ed25519VerificationKey2018: https://w3id.org/security/v2
JSONWebKey: https://w3id.org/security/jws/v1
BBS: https://w3id.org/security/bbs/v1
EcdsaSecp256k1VerificationKey2019: https://w3id.org/security/v2
Ed25519VerificationKey2020: TBD

**Comment by OR13** [comment]
rather than have 6 contexts... perhapse we can work together to define `https://w3id.org/sidetree/v1` ?

**Comment by troyronda** [comment]
Looks like there are new URIs:

Ed25519VerificationKey2018: https://w3id.org/security/suites/ed25519-2018
JsonWebKey2020: https://w3id.org/security/suites/jws-2020/v1
Bls12381G2Key2020: https://w3id.org/security/suites/bls12381-2020
EcdsaSecp256k1VerificationKey2019: https://w3id.org/security/suites/secp256k1-2019
Ed25519VerificationKey2020: https://w3id.org/security/suites/ed25519-2020
