### ISSUE TITLE
Update protocol parameters 

### ISSUE THREAD

**Issue by sandrask** [trustbloc/sidetree-core-go#84]
Add new parameters:

Maximum anchor file size | The maximum compressed anchor file size. 
Maximum batch file size | The maximum compressed batch file size. 
Maximum encoded hash length | The maximum accepted string length of an encoded hash. 

Also look for any additional changes here:
https://github.com/decentralized-identity/sidetree/blob/master/docs/protocol.md#sidetree-protocol-versioning--parameters

**Comment by troyronda** [comment]
@Moopli @sandrask @bstasyszyn we also need to expose some of these parameters to the client via well-known.

**Comment by sandrask** [comment]
The above mentioned parameters have been handled with implementation of batch files (anchor, map, chunk) and encoded hash length is no longer used in reference implementation.
